name: Release

on:
  release:
    types: [created]

jobs:
  bundle:
    runs-on: ubuntu-latest
    name: Bundle
    steps:
      - uses: actions/checkout@v4

      - name: Build GDOv1-S bundle
        run:  |
          mkdir GarageDoorOpenerGDOv1S
          cp bundles/gdov1-s.txt GarageDoorOpenerGDOv1S/install.txt
          cp bundles/gdov1-s.txt GarageDoorOpenerGDOv1S/update.txt
          cp konnected-gdov1-s.groovy GarageDoorOpenerGDOv1S/konnected.KonnectedGarageDoorGDOv1S.groovy
          wget -O GarageDoorOpenerGDOv1S/esphome.espHomeApiHelper.groovy https://raw.githubusercontent.com/konnected-io/hubitat-public/main/ESPHome/ESPHome-API-Library.groovy

      - name: Zip bundles
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          path: GarageDoorOpenerGDOv1S
          filename: GarageDoorOpenerGDOv1S.zip

      - name: Upload to Release
        uses: Shopify/upload-to-release@v2.0.0
        with:
          name: GarageDoorOpenerGDOv1S.zip
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      